#ifndef GRAMMAR_H
#define GRAMMAR_H

using namespace cc;

/* Generated by neoast */
typedef void CCBuffers;

extern "C" {
cc::ASTGlobal* cc_parse(void* error_ctx, CCBuffers* buffers, const char* input);

CCBuffers* cc_allocate_buffers();
void cc_free_buffers(CCBuffers*);
unsigned int cc_init();
void cc_free();
}

int handle_keyword(Context* ctx, const char* text, void* yyval);

#endif //GRAMMAR_H
